apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: lucasycosta/nginx:$IMAGE_TAG
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name:  nginx
spec:
  selector:
    app:  nginx
  type:  LoadBalancer
  ports:
  - port:  80
    targetPort:  80