name: create-build-image
on:
  push:
    branches: ["master"] 
  workflow_dispatch: 
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: obter código local
      uses: actions/checkout@v4
    - name: login docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build da imagem
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: lucasycosta/nginx:${{github.run_number}}


