name: create-build-image
on:
  push:
    branches: ["master"] 
  workflow_dispatch: 
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: obter código local
      uses: actions/checkout@v4
    - name: login docker
      uses: docker/login-action@v3
      with:
        username: ${{secrets.USER_DOCKER}}
        password: $${{secrets.PASS_DOCKER}}


