name: primeira-pipeline                       # nome do workflow
on:                                           # triger que irá disparar a ação
  push:                                       # o gatilho é um commit 
    branches: ["master"]                      # branches em que o commit dispara o triger
  workflow_dispatch:                          # permite execução manual
jobs:                                         # tarefas
  primeiro-job:                               # inicio da declaração do job
    name: "Meu primeiro job"
    runs-on: ubuntu-latest                    # runner do job
    steps:                                    # passos de execução
      - name: "Minha primeira ação"
        
        run: echo "Hello Worls"               # comando que será executado
      - name: "Segunda ação"
        run: |
          echo "Criação da primeira pipeline e workflow"
          echo "Uhuuuuuuuuuuuuu"
      - name: "Teste SHELL"
        run: |
          variavel = "Testeeeeeeeeeeeeeeeeeeeeee"
          print(variavel)
        shell: python                         # tipo do terminal, permite executar diferentes comandos
  segundo-job:                               
    name: "Meu segundo job"
    runs-on: ubuntu-latest                 
    steps:    
      - name: "Verificação da versão do NodJS atual"
        run: node --version
      - name: "Definição da versão 22.13.0 do NodeJS"
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "22.13.0"
      - name: "Nova Verificação"
        run: node --version
        
    
